services:
  webhook:
    container_name: webhook_listener
    build:
      context: .
    ports:  #[]
      - "5002:5002" # accesible port to the Host machine
    expose:
      - "5002"     # Internal port only (accessible to other containers within docker)
    restart: unless-stopped

  nginx:
    container_name: nginx_proxy
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80" # Exposes container port 80 on host port 33221
    depends_on:
      - webhook
    restart: unless-stopped
